# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yel-yaqi <yel-yaqi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/18 16:34:00 by yel-yaqi          #+#    #+#              #
#    Updated: 2024/03/18 19:43:39 by yel-yaqi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = philo
CFLAGS = -Wall -Wextra -Werror
SOURCES = main.c arg_verify.c satoi.c main_logic.c

$(NAME): $(SOURCES) Makefile #NOTE: ADD CFLAGS LATER
	cc $(SOURCES)  -o $@